version: '3'

services:

  docsify:
    build:
      dockerfile: Dockerfile
      context: .
    image: mspintegrations/docsify:latest
    volumes:
      - './src/:/usr/local/docsify/'
    ports:
      - '85:3000'
    networks:
      - frontend

networks:
  frontend:
